# Generated by Django 4.2.9 on 2024-09-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcapfileupload',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_exports/', verbose_name='CSV data export'),
        ),
        migrations.AddField(
            model_name='pcapfileupload',
            name='ftp_data_file',
            field=models.FileField(blank=True, null=True, upload_to='fpt_data_exports/'),
        ),
        migrations.AddField(
            model_name='pcapfileupload',
            name='http_data_file',
            field=models.FileField(blank=True, null=True, upload_to='http_data_exports/'),
        ),
        migrations.AddField(
            model_name='pcapfileupload',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to='json_exports/'),
        ),
        migrations.AddField(
            model_name='pcapfileupload',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='pcapfileupload',
            name='smtp_file',
            field=models.FileField(blank=True, null=True, upload_to='smtp_exports/'),
        ),
        migrations.AddField(
            model_name='pcapfileupload',
            name='snmp_file',
            field=models.FileField(blank=True, null=True, upload_to='snmp_exports/'),
        ),
        migrations.AddField(
            model_name='pcapfileupload',
            name='ssh_file',
            field=models.FileField(blank=True, null=True, upload_to='ssh_exports/'),
        ),
        migrations.AddField(
            model_name='pcapfileupload',
            name='telnet_file',
            field=models.FileField(blank=True, null=True, upload_to='telnet_exports/'),
        ),
        migrations.AddField(
            model_name='pcapfileupload',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='docx_exports/'),
        ),
        migrations.AddField(
            model_name='pcapfileupload',
            name='tls_session_key',
            field=models.FileField(blank=True, null=True, upload_to='tls_session_exports/'),
        ),
        migrations.AddField(
            model_name='pcapfileupload',
            name='xml_file',
            field=models.FileField(blank=True, null=True, upload_to='xml_exports/'),
        ),
    ]
