# Generated by Django 4.2.9 on 2024-09-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pcapfileupload_csv_file_pcapfileupload_ftp_data_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcapfileupload',
            name='analysis_json_file',
            field=models.FileField(blank=True, null=True, upload_to='json_data_analysis/'),
        ),
    ]
