# Generated by Django 4.2.9 on 2024-09-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pcapfileupload_analysis_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcapfileupload',
            name='status_completed',
            field=models.BooleanField(default=False),
        ),
    ]
